---
- name: Remove default nginx vhost config file (if configured).
  file:
    path: "{{ nginx_default_vhost_path }}"
    state: absent
 # when: nginx_remove_default_vhost
  notify:
    - reload nginx

- name: Add managed vhost config file app .
  template:
    src: vhosts.j2
    dest: "{{ nginx_vhost_path }}/vhosts.conf"
    mode: 0644
  when: ansible_nodename | search(".*app*")
  notify:
    - reload nginx

- name: Add managed vhost config file for web/ LB.
  template:
    src: lb.conf.j2
    dest: "{{ nginx_vhost_path }}/vhosts.conf"
    mode: 0644
  when: ansible_nodename | search(".*web*")
  notify:
    - reload nginx

- name: Remove managed vhost config file (if no vhosts are configured).
  file:
    path: "{{ nginx_vhost_path }}/vhosts.conf"
    state: absent
  when: nginx_vhosts|length == 0
  notify:
    - reload nginx

